name: Deployment
on: push
jobs:
  deploy:
#    continue-on-error: true
#    strategy:
#      matrix:
#        os: [ubuntu-latest, windows-latest]
#    runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: Get access to code
        uses: actions/checkout@v3
      - name: Install java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        run: mvn clean compile
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: build
      - name: Deploy
        run: echo Deployment...