name: Testing
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get access to code
        uses: actions/checkout@v3
      - name: Install java
        uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'adopt'
            cache: 'maven'
      - name: Testing
        run: mvn test